-- ============================================================================
-- 0014 — Tabelas GoJet (parkings/bikes/parking_history) + cron scrape-gojet/gerar-slots
-- Capturada do banco em 17/06/2026 (pg_get_functiondef / cron.job / information_schema).
-- Estes objetos foram originalmente aplicados via SQL editor; este arquivo versiona o
-- estado real. Idempotente (CREATE IF NOT EXISTS / cron.schedule por nome).
-- ============================================================================

create extension if not exists pg_cron;
create extension if not exists pg_net;

-- ── parkings: estado atual de cada parking por cidade ───────────────────────
create table if not exists public.parkings (
  id                text not null,
  city_id           text not null,
  cidade            text,
  geo               geography(Point,4326),
  nome              text,
  bikes_total       integer,
  bikes_disponiveis integer,
  dados             jsonb,
  atualizado_em     timestamptz not null default now(),
  primary key (city_id, id)
);
create index if not exists idx_parkings_city on public.parkings(city_id);
create index if not exists idx_parkings_geo  on public.parkings using gist(geo);

-- ── bikes: estado atual de cada bike por cidade ─────────────────────────────
create table if not exists public.bikes (
  id            text not null,
  city_id       text not null,
  cidade        text,
  geo           geography(Point,4326),
  status        text,           -- available|reserved|renting|maintenance|low_battery
  bateria       integer,        -- 0–100
  last_order_at timestamptz,
  dados         jsonb,
  atualizado_em timestamptz not null default now(),
  primary key (city_id, id)
);
create index if not exists idx_bikes_city   on public.bikes(city_id);
create index if not exists idx_bikes_status on public.bikes(city_id, status);
create index if not exists idx_bikes_geo    on public.bikes using gist(geo);

-- ── parking_history: bikes disponíveis por bucket de 15 min ─────────────────
create table if not exists public.parking_history (
  id                bigint generated by default as identity primary key,
  city_id           text,
  parking_id        text,
  bikes_disponiveis integer,
  bucket_ts         timestamptz not null,
  criado_em         timestamptz not null default now()
);
create unique index if not exists uq_phist_bucket on public.parking_history(city_id, parking_id, bucket_ts);
create index if not exists idx_phist_bucket on public.parking_history(bucket_ts desc);

-- RLS: leitura para autenticados; escrita só service_role (scrape-gojet ignora RLS).
alter table public.parkings        enable row level security;
alter table public.bikes           enable row level security;
alter table public.parking_history enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='parkings' and policyname='parkings_sel') then
    create policy parkings_sel on public.parkings for select using (auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename='bikes' and policyname='bikes_sel') then
    create policy bikes_sel on public.bikes for select using (auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename='parking_history' and policyname='phist_sel') then
    create policy phist_sel on public.parking_history for select using (auth.role() = 'authenticated');
  end if;
end $$;

-- ── Agendamentos pg_cron (chave publishable/anon — pública por design) ───────
select cron.schedule('scrape-gojet-15min', '*/15 * * * *', $$
  select net.http_post(
    url := 'https://ducdbrupxpzqcblfreqn.supabase.co/functions/v1/scrape-gojet',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer sb_publishable_HOGHrfrftyLTkHfGGFsKFg_jNlydshc',
      'apikey','sb_publishable_HOGHrfrftyLTkHfGGFsKFg_jNlydshc'),
    body := '{}'::jsonb
  );
$$);

select cron.schedule('gerar-slots-diario', '0 0 * * *', $$
  select net.http_post(
    url := 'https://ducdbrupxpzqcblfreqn.supabase.co/functions/v1/gerar-slots',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer sb_publishable_HOGHrfrftyLTkHfGGFsKFg_jNlydshc',
      'apikey','sb_publishable_HOGHrfrftyLTkHfGGFsKFg_jNlydshc'),
    body := '{}'::jsonb
  );
$$);
