-- 0036 — Tabelas necessárias p/ Edge Functions portadas do Firebase Cloud Functions.
-- gojet_snapshots, monitor_config, monitor_alertas, config_auto_slots,
-- logs_automacao, log_slots_auto, tarefas (monitor).
-- Idempotente (CREATE IF NOT EXISTS).

-- ── gojet_snapshots: snapshots periódicos de parkings/bikes GoJet ──
create table if not exists public.gojet_snapshots (
  id         text primary key,
  data       jsonb not null default '[]'::jsonb,
  criado_em  timestamptz not null default now()
);
alter table public.gojet_snapshots enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='gojet_snapshots' and policyname='gojet_snap_sel') then
    create policy gojet_snap_sel on public.gojet_snapshots for select using (auth.role() = 'authenticated');
  end if;
end $$;

-- ── monitor_config: configuração de monitoramento por cidade ──
create table if not exists public.monitor_config (
  id              text primary key,
  cidade          text not null,
  ativo           boolean not null default true,
  tipo_monitor    text,
  config          jsonb not null default '{}'::jsonb,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz not null default now()
);
alter table public.monitor_config enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='monitor_config' and policyname='monconf_sel') then
    create policy monconf_sel on public.monitor_config for select using (auth.role() = 'authenticated');
  end if;
end $$;

-- ── monitor_alertas: alertas de GPS/SLA/geofence ──
create table if not exists public.monitor_alertas (
  id          bigint generated by default as identity primary key,
  tipo        text not null,
  uid         text,
  slot_id     text,
  tarefa_id   text,
  mensagem    text,
  dados       jsonb,
  criado_em   timestamptz not null default now()
);
create index if not exists idx_mon_alertas_tipo_uid on public.monitor_alertas(tipo, uid, criado_em desc);
alter table public.monitor_alertas enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='monitor_alertas' and policyname='monalert_sel') then
    create policy monalert_sel on public.monitor_alertas for select using (auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename='monitor_alertas' and policyname='monalert_ins') then
    create policy monalert_ins on public.monitor_alertas for insert with check (true);
  end if;
end $$;

-- ── config_auto_slots: configuração do motor inteligente de slots ──
create table if not exists public.config_auto_slots (
  id              text primary key,
  cidade          text not null,
  ativo           boolean not null default true,
  config          jsonb not null default '{}'::jsonb,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz not null default now()
);
alter table public.config_auto_slots enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='config_auto_slots' and policyname='cas_sel') then
    create policy cas_sel on public.config_auto_slots for select using (auth.role() = 'authenticated');
  end if;
end $$;

-- ── logs_automacao: log de execução de automações ──
create table if not exists public.logs_automacao (
  id          bigint generated by default as identity primary key,
  tipo        text not null,
  dados       jsonb,
  criado_em   timestamptz not null default now()
);
alter table public.logs_automacao enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='logs_automacao' and policyname='logaut_sel') then
    create policy logaut_sel on public.logs_automacao for select using (auth.role() = 'authenticated');
  end if;
end $$;

-- ── log_slots_auto: log do motor inteligente de slots ──
create table if not exists public.log_slots_auto (
  id          bigint generated by default as identity primary key,
  cidade      text,
  dados       jsonb,
  criado_em   timestamptz not null default now()
);
alter table public.log_slots_auto enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='log_slots_auto' and policyname='lsa_sel') then
    create policy lsa_sel on public.log_slots_auto for select using (auth.role() = 'authenticated');
  end if;
end $$;

-- ── tarefas: tarefas de monitor (M1/M2/M3), distintas de tarefas_logistica ──
create table if not exists public.tarefas (
  id              text primary key default gen_random_uuid()::text,
  tipo            text,
  estacao_id      text,
  cidade          text,
  status          text not null default 'aberto',
  prioridade      text default 'normal',
  descricao       text,
  dados           jsonb,
  criado_por      text,
  atribuido_a     text,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz not null default now()
);
create index if not exists idx_tarefas_status on public.tarefas(status, cidade);
alter table public.tarefas enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='tarefas' and policyname='tarefas_sel') then
    create policy tarefas_sel on public.tarefas for select using (auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename='tarefas' and policyname='tarefas_ins') then
    create policy tarefas_ins on public.tarefas for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='tarefas' and policyname='tarefas_upd') then
    create policy tarefas_upd on public.tarefas for update using (true);
  end if;
end $$;

-- ── Cron jobs para as novas Edge Functions ──

-- Automação: limpeza de snapshots (03:00 diário)
select cron.schedule('limpeza-snapshots-diario', '0 3 * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"limpeza-snapshots"}'::jsonb
  );
$$);

-- Automação: gerar slots (21:00 diário)
select cron.schedule('automacao-gerar-slots', '0 21 * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"gerar-slots"}'::jsonb
  );
$$);

-- GoJet scraper (a cada 15min — substitui o cron do 0014)
select cron.schedule('automacao-gojet-15min', '*/15 * * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao-gojet',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"scraper"}'::jsonb
  );
$$);

-- Tarefas agendado (a cada hora)
select cron.schedule('tarefas-agendado-1h', '0 * * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao-tarefas',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"gerar-tarefas-agendado"}'::jsonb
  );
$$);

-- Slots inteligente (a cada 15min)
select cron.schedule('slots-inteligente-15min', '*/15 * * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao-tarefas',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"gerar-slots-inteligente"}'::jsonb
  );
$$);

-- SLA escalation (a cada 5min)
select cron.schedule('escalar-sla-5min', '*/5 * * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao-tarefas',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"escalar-slots-sla"}'::jsonb
  );
$$);

-- GPS alertas: verificar atrasos (a cada 5min)
select cron.schedule('gps-alertas-5min', '*/5 * * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/gps-alertas',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"verificar-atrasos"}'::jsonb
  );
$$);

-- Historico parking diário (23:55)
select cron.schedule('historico-parking-diario', '55 23 * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/automacao-tarefas',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"salvar-historico-parking"}'::jsonb
  );
$$);

-- Relatório Guard diário (07:00 ter-dom)
select cron.schedule('relatorio-guard-diario', '0 7 * * 2-7', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/relatorios',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"guard-diario"}'::jsonb
  );
$$);

-- Relatório Guard semanal (segunda 07:00)
select cron.schedule('relatorio-guard-semanal', '0 7 * * 1', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/relatorios',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"guard-semanal"}'::jsonb
  );
$$);

-- Relatório Perdas diário (08:00)
select cron.schedule('relatorio-perdas-diario', '0 8 * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/relatorios',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"perdas-diario"}'::jsonb
  );
$$);

-- Relatório Perdas semanal (segunda 08:00)
select cron.schedule('relatorio-perdas-semanal', '0 8 * * 1', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/relatorios',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"perdas-semanal"}'::jsonb
  );
$$);

-- Slots Telegram: resumo (08:00 e 20:00)
select cron.schedule('slots-resumo-manha', '0 8 * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/slots-telegram',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"resumo"}'::jsonb
  );
$$);

select cron.schedule('slots-resumo-noite', '0 20 * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/slots-telegram',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"resumo"}'::jsonb
  );
$$);

-- Slots Telegram: confirmar cascata (a cada 15min)
select cron.schedule('slots-cascata-15min', '*/15 * * * *', $$
  select net.http_post(
    url := current_setting('app.settings.supabase_url') || '/functions/v1/slots-telegram',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || current_setting('app.settings.service_role_key')),
    body := '{"action":"confirmar-cascata"}'::jsonb
  );
$$);
