-- 0065_missing_tables_pre_shutdown.sql
-- Firestore → Supabase: cria tabelas faltantes + adiciona colunas ausentes
-- em tabelas existentes. Idempotente (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- ============================================================================

-- ════════════════════════════════════════════════════════════════════════════
-- 1. COLUNAS FALTANTES EM TABELAS EXISTENTES
-- ════════════════════════════════════════════════════════════════════════════

-- gojet_snapshots: schema atual é (id text, data jsonb, criado_em).
-- O scraper Firestore salva cidade, cityId, parkings, bikes, total, savedAt, etc.
alter table public.gojet_snapshots add column if not exists cidade        text;
alter table public.gojet_snapshots add column if not exists city_id       text;
alter table public.gojet_snapshots add column if not exists parkings      jsonb;
alter table public.gojet_snapshots add column if not exists bikes         jsonb;
alter table public.gojet_snapshots add column if not exists total_parkings int;
alter table public.gojet_snapshots add column if not exists total_bikes    int;
alter table public.gojet_snapshots add column if not exists chunked       boolean default false;
alter table public.gojet_snapshots add column if not exists total_chunks  int;
alter table public.gojet_snapshots add column if not exists chunk         int;
alter table public.gojet_snapshots add column if not exists saved_at      timestamptz;
alter table public.gojet_snapshots add column if not exists atualizado_em timestamptz;

create index if not exists idx_gojet_snap_cidade_saved
  on public.gojet_snapshots (cidade, saved_at desc);

-- log_slots_auto: faltam data, slots_criados, detalhes
alter table public.log_slots_auto add column if not exists data          date;
alter table public.log_slots_auto add column if not exists slots_criados int;
alter table public.log_slots_auto add column if not exists detalhes      jsonb;

-- monitor_alertas: falta resolvido
alter table public.monitor_alertas add column if not exists resolvido boolean default false;
alter table public.monitor_alertas add column if not exists msg       text;

-- service_role full access nas tabelas existentes que podem não ter
do $$ begin
  if not exists (select 1 from pg_policies where tablename='gojet_snapshots' and policyname='gojet_snap_svc') then
    create policy gojet_snap_svc on public.gojet_snapshots for all to service_role using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='monitor_alertas' and policyname='monalert_svc') then
    create policy monalert_svc on public.monitor_alertas for all to service_role using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='log_slots_auto' and policyname='lsa_svc') then
    create policy lsa_svc on public.log_slots_auto for all to service_role using (true);
  end if;
end $$;

-- ════════════════════════════════════════════════════════════════════════════
-- 2. TABELAS NOVAS
-- ════════════════════════════════════════════════════════════════════════════

-- ── slot_alertas ─────────────────────────────────────────────────────────────
create table if not exists public.slot_alertas (
  id        bigint generated by default as identity primary key,
  slot_id   text,
  tipo      text,
  msg       text,
  criado_em timestamptz not null default now()
);
create index if not exists idx_slot_alertas_slot on public.slot_alertas (slot_id);
alter table public.slot_alertas enable row level security;
create policy slot_alertas_svc  on public.slot_alertas for all to service_role using (true);
create policy slot_alertas_sel  on public.slot_alertas for select to authenticated using (true);
create policy slot_alertas_ins  on public.slot_alertas for insert to authenticated with check (true);

-- ── slot_lembretes ───────────────────────────────────────────────────────────
create table if not exists public.slot_lembretes (
  id         bigint generated by default as identity primary key,
  slot_id    text,
  uid        text,
  enviado_em timestamptz,
  tipo       text,
  criado_em  timestamptz not null default now()
);
create index if not exists idx_slot_lembretes_slot on public.slot_lembretes (slot_id);
alter table public.slot_lembretes enable row level security;
create policy slot_lembretes_svc on public.slot_lembretes for all to service_role using (true);
create policy slot_lembretes_sel on public.slot_lembretes for select to authenticated using (true);
create policy slot_lembretes_ins on public.slot_lembretes for insert to authenticated with check (true);

-- ── bug_reports ──────────────────────────────────────────────────────────────
create table if not exists public.bug_reports (
  id             bigint generated by default as identity primary key,
  uid            text,
  email          text,
  descricao      text,
  screenshot_url text,
  user_agent     text,
  url            text,
  criado_em      timestamptz not null default now()
);
alter table public.bug_reports enable row level security;
create policy bug_reports_svc on public.bug_reports for all to service_role using (true);
create policy bug_reports_sel on public.bug_reports for select to authenticated using (true);
create policy bug_reports_ins on public.bug_reports for insert to authenticated with check (true);

-- ── eventos ──────────────────────────────────────────────────────────────────
create table if not exists public.eventos (
  id        bigint generated by default as identity primary key,
  cidade    text,
  tipo      text,
  titulo    text,
  descricao text,
  dados     jsonb,
  criado_em timestamptz not null default now()
);
create index if not exists idx_eventos_cidade on public.eventos (cidade, criado_em desc);
alter table public.eventos enable row level security;
create policy eventos_svc on public.eventos for all to service_role using (true);
create policy eventos_sel on public.eventos for select to authenticated using (true);
create policy eventos_ins on public.eventos for insert to authenticated with check (true);

-- ── eficiencias_logistica ────────────────────────────────────────────────────
create table if not exists public.eficiencias_logistica (
  id                 bigint generated by default as identity primary key,
  uid                text,
  cidade             text,
  data               date,
  tarefas_concluidas int,
  tempo_medio_min    numeric,
  km_rodados         numeric,
  dados              jsonb,
  criado_em          timestamptz not null default now(),
  unique (uid, data)
);
create index if not exists idx_efic_cidade on public.eficiencias_logistica (cidade, data desc);
alter table public.eficiencias_logistica enable row level security;
create policy efic_svc on public.eficiencias_logistica for all to service_role using (true);
create policy efic_sel on public.eficiencias_logistica for select to authenticated using (true);
create policy efic_ins on public.eficiencias_logistica for insert to authenticated with check (true);
create policy efic_upd on public.eficiencias_logistica for update to authenticated using (true) with check (true);

-- ── notificacoes_app ─────────────────────────────────────────────────────────
create table if not exists public.notificacoes_app (
  id        bigint generated by default as identity primary key,
  uid       text,
  titulo    text,
  corpo     text,
  tipo      text,
  lida      boolean not null default false,
  dados     jsonb,
  criado_em timestamptz not null default now()
);
create index if not exists idx_notif_uid_lida on public.notificacoes_app (uid, lida);
alter table public.notificacoes_app enable row level security;
create policy notif_svc  on public.notificacoes_app for all to service_role using (true);
create policy notif_sel  on public.notificacoes_app for select to authenticated using (uid = auth.uid()::text);
create policy notif_upd  on public.notificacoes_app for update to authenticated using (uid = auth.uid()::text) with check (uid = auth.uid()::text);
create policy notif_ins  on public.notificacoes_app for insert to authenticated with check (true);

-- ── meis ─────────────────────────────────────────────────────────────────────
create table if not exists public.meis (
  id           bigint generated by default as identity primary key,
  uid          text unique,
  cnpj         text,
  razao_social text,
  ativo        boolean not null default true,
  dados        jsonb,
  criado_em    timestamptz not null default now()
);
alter table public.meis enable row level security;
create policy meis_svc on public.meis for all to service_role using (true);
create policy meis_sel on public.meis for select to authenticated using (true);
create policy meis_ins on public.meis for insert to authenticated with check (true);
create policy meis_upd on public.meis for update to authenticated using (uid = auth.uid()::text) with check (uid = auth.uid()::text);

-- ════════════════════════════════════════════════════════════════════════════
-- 3. SEED app_settings COM CHAVES DE CONFIG FALTANTES
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO public.app_settings (chave, valor) VALUES
  ('monitor_config',    '{}'::jsonb),
  ('slot_config',       '{}'::jsonb),
  ('config_logistica',  '{}'::jsonb),
  ('guard_config',      '{}'::jsonb)
ON CONFLICT (chave) DO NOTHING;
