-- 0066_inventario_config_logistica.sql
-- Tabelas faltantes para o GestorLogisticaPanel funcionar 100% Supabase.
-- Idempotente (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- ============================================================================

-- ════════════════════════════════════════════════════════════════════════════
-- 1. COLUNAS FALTANTES EM TABELAS EXISTENTES
-- ════════════════════════════════════════════════════════════════════════════

-- meis: o painel usa nome, cpf, cnpj, status, cidade, suspenso_inicio,
-- suspenso_ate, motivo_suspensao — a tabela existente tem uid, cnpj,
-- razao_social, ativo, dados. Adicionar colunas que faltam.
alter table public.meis add column if not exists nome              text;
alter table public.meis add column if not exists cpf               text;
alter table public.meis add column if not exists status            text default 'ATIVO';
alter table public.meis add column if not exists cidade            text;
alter table public.meis add column if not exists suspenso_inicio   date;
alter table public.meis add column if not exists suspenso_ate      date;
alter table public.meis add column if not exists motivo_suspensao  text;
alter table public.meis add column if not exists atualizado_em     timestamptz;

create index if not exists idx_meis_cidade on public.meis (cidade);

-- eficiencias_logistica: o painel usa nome, movimentacoes, baterias, obs —
-- a tabela existente tem tarefas_concluidas, tempo_medio_min, km_rodados.
alter table public.eficiencias_logistica add column if not exists nome           text;
alter table public.eficiencias_logistica add column if not exists movimentacoes  int default 0;
alter table public.eficiencias_logistica add column if not exists baterias       int default 0;
alter table public.eficiencias_logistica add column if not exists obs            text;

-- ════════════════════════════════════════════════════════════════════════════
-- 2. TABELAS NOVAS
-- ════════════════════════════════════════════════════════════════════════════

-- ── inventario ──────────────────────────────────────────────────────────────
-- Consolidação: em vez de inventario_armario, inventario_patinete, etc.,
-- uma única tabela com coluna 'tipo'.
create table if not exists public.inventario (
  id            bigint generated by default as identity primary key,
  tipo          text not null,           -- armario, patinete, carro, suporte
  nome          text not null,
  identificador text,
  zona          text,
  status        text not null default 'ATIVO',
  observacao    text,
  cidade        text,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz
);
create index if not exists idx_inventario_tipo_cidade on public.inventario (tipo, cidade);
alter table public.inventario enable row level security;
create policy inventario_svc on public.inventario for all to service_role using (true);
create policy inventario_sel on public.inventario for select to authenticated using (true);
create policy inventario_ins on public.inventario for insert to authenticated with check (true);
create policy inventario_upd on public.inventario for update to authenticated using (true) with check (true);
create policy inventario_del on public.inventario for delete to authenticated using (true);

-- ── config_logistica ────────────────────────────────────────────────────────
-- Configuração por cidade (ou 'global'). Antes era documento Firestore.
create table if not exists public.config_logistica (
  cidade              text primary key,  -- ex: 'SP', 'CWB', 'global'
  sla_minutos         int default 120,
  raio_sugestao_km    numeric default 2,
  alerta_zero_gojet   boolean default true,
  threshold_bat_baixa int default 30,
  confirmacao_min     int default 120,
  reabertura_sem_conf_min int default 90,
  prazo_horas         jsonb default '{}'::jsonb,
  criado_em           timestamptz not null default now(),
  atualizado_em       timestamptz
);
alter table public.config_logistica enable row level security;
create policy cfg_log_svc on public.config_logistica for all to service_role using (true);
create policy cfg_log_sel on public.config_logistica for select to authenticated using (true);
create policy cfg_log_ups on public.config_logistica for insert to authenticated with check (true);
create policy cfg_log_upd on public.config_logistica for update to authenticated using (true) with check (true);

-- ── telegram_grupos ─────────────────────────────────────────────────────────
-- Antes era documento Firestore telegram_config/cidades com nested maps.
-- Agora uma tabela normalizada.
create table if not exists public.telegram_grupos (
  id        bigint generated by default as identity primary key,
  cidade    text not null,               -- 'SP', 'CWB', 'global'
  tipo      text not null,               -- 'scout', 'charger', 'geral', ...
  chat_id   text not null,
  nome      text,
  topicos   jsonb default '{}'::jsonb,   -- cargo → threadId
  criado_em timestamptz not null default now(),
  unique (cidade, tipo)
);
alter table public.telegram_grupos enable row level security;
create policy tg_grupos_svc on public.telegram_grupos for all to service_role using (true);
create policy tg_grupos_sel on public.telegram_grupos for select to authenticated using (true);
create policy tg_grupos_ups on public.telegram_grupos for insert to authenticated with check (true);
create policy tg_grupos_upd on public.telegram_grupos for update to authenticated using (true) with check (true);

-- ════════════════════════════════════════════════════════════════════════════
-- 3. RLS para meis UPDATE/DELETE aberto a authenticated (gestores)
-- ════════════════════════════════════════════════════════════════════════════
do $$ begin
  -- Drop the restrictive policy that only lets user update own MEI
  if exists (select 1 from pg_policies where tablename='meis' and policyname='meis_upd') then
    drop policy meis_upd on public.meis;
  end if;
end $$;
create policy meis_upd on public.meis for update to authenticated using (true) with check (true);
do $$ begin
  if not exists (select 1 from pg_policies where tablename='meis' and policyname='meis_del') then
    create policy meis_del on public.meis for delete to authenticated using (true);
  end if;
end $$;

-- eficiencias_logistica: allow delete
do $$ begin
  if not exists (select 1 from pg_policies where tablename='eficiencias_logistica' and policyname='efic_del') then
    create policy efic_del on public.eficiencias_logistica for delete to authenticated using (true);
  end if;
end $$;
