-- 0067_remaining_firestore_tables.sql
-- Cria tabelas/colunas faltantes para migrar as 22 coleções restantes do Firestore.
-- Idempotente (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- ============================================================================

-- ════════════════════════════════════════════════════════════════════════════
-- 1. COLUNAS FALTANTES EM TABELAS EXISTENTES
-- ════════════════════════════════════════════════════════════════════════════

-- slot_alertas: CF escreve cidade, vagas_reabertas, aceite_ids
alter table public.slot_alertas add column if not exists cidade           text;
alter table public.slot_alertas add column if not exists vagas_reabertas  int;
alter table public.slot_alertas add column if not exists aceite_ids       text[];
alter table public.slot_alertas add column if not exists slot_id_ref      text;
create index if not exists idx_slot_alertas_cidade on public.slot_alertas (cidade, criado_em desc);

-- slot_lembretes: CF escreve nome, cnpj, fase, min_restantes, cidade, aceite_id
alter table public.slot_lembretes add column if not exists aceite_id      text;
alter table public.slot_lembretes add column if not exists nome           text;
alter table public.slot_lembretes add column if not exists cnpj           text;
alter table public.slot_lembretes add column if not exists fase           int;
alter table public.slot_lembretes add column if not exists min_restantes  int;
alter table public.slot_lembretes add column if not exists cidade         text;
create index if not exists idx_slot_lembretes_cidade on public.slot_lembretes (cidade, criado_em desc);

-- eventos: campos GoJet point linking
alter table public.eventos add column if not exists nome                    text;
alter table public.eventos add column if not exists estado                  text;
alter table public.eventos add column if not exists pais                    text;
alter table public.eventos add column if not exists inicio                  timestamptz;
alter table public.eventos add column if not exists fim                     timestamptz;
alter table public.eventos add column if not exists ponto_gojet_estacao_id  text;
alter table public.eventos add column if not exists ponto_gojet_lat         numeric;
alter table public.eventos add column if not exists ponto_gojet_lng         numeric;
alter table public.eventos add column if not exists ponto_gojet_target      int;
alter table public.eventos add column if not exists ponto_gojet_raio        int;
alter table public.eventos add column if not exists firebase_id             text;
alter table public.eventos add column if not exists atualizado_em           timestamptz;
-- policy update
do $$ begin
  if not exists (select 1 from pg_policies where tablename='eventos' and policyname='eventos_upd') then
    create policy eventos_upd on public.eventos for update to authenticated using (true) with check (true);
  end if;
end $$;

-- ════════════════════════════════════════════════════════════════════════════
-- 2. TABELAS NOVAS
-- ════════════════════════════════════════════════════════════════════════════

-- ── monitor_config ──────────────────────────────────────────────────────────
-- Configuração de monitor por cidade com 3 níveis (M1/M2/M3)
create table if not exists public.monitor_config (
  cidade             text primary key,
  m1                 jsonb default '{}'::jsonb,
  m2                 jsonb default '{}'::jsonb,
  m3                 jsonb default '{}'::jsonb,
  atualizado_em      timestamptz
);
alter table public.monitor_config enable row level security;
create policy mc_svc on public.monitor_config for all to service_role using (true);
create policy mc_sel on public.monitor_config for select to authenticated using (true);
create policy mc_ups on public.monitor_config for insert to authenticated with check (true);
create policy mc_upd on public.monitor_config for update to authenticated using (true) with check (true);

-- ── guard_config ────────────────────────────────────────────────────────────
-- Regiões + controle de perdas (antes 2 docs Firestore)
create table if not exists public.guard_regioes (
  cidade   text primary key,
  regiao   text,
  filial   text
);
alter table public.guard_regioes enable row level security;
create policy gr_svc on public.guard_regioes for all to service_role using (true);
create policy gr_sel on public.guard_regioes for select to authenticated using (true);
create policy gr_ups on public.guard_regioes for insert to authenticated with check (true);
create policy gr_upd on public.guard_regioes for update to authenticated using (true) with check (true);

create table if not exists public.guard_controle_perdas (
  id                bigint generated by default as identity primary key,
  filial            text,
  regiao            text,
  responsavel       text,
  patins            int default 0,
  bikes             int default 0,
  brpd              int default 0,
  vand_total        int default 0,
  nao_enc_patins    int default 0,
  nao_enc_bikes     int default 0,
  nao_enc_bat       int default 0,
  status1_24h       text,
  status2_7d        text,
  atualizado_em     timestamptz
);
alter table public.guard_controle_perdas enable row level security;
create policy gcp_svc on public.guard_controle_perdas for all to service_role using (true);
create policy gcp_sel on public.guard_controle_perdas for select to authenticated using (true);
create policy gcp_ups on public.guard_controle_perdas for insert to authenticated with check (true);
create policy gcp_upd on public.guard_controle_perdas for update to authenticated using (true) with check (true);
create policy gcp_del on public.guard_controle_perdas for delete to authenticated using (true);

-- ── operacoes ───────────────────────────────────────────────────────────────
-- CRUD de operações logísticas (antes via callable CFs)
create table if not exists public.operacoes (
  id              bigint generated by default as identity primary key,
  uid             text,
  tipo            text,
  status          text not null default 'pendente',
  prioridade      text,
  estacao_id      text,
  quantidade      int,
  notas           text,
  data_vencimento timestamptz,
  cidade          text,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz
);
create index if not exists idx_operacoes_cidade on public.operacoes (cidade, criado_em desc);
create index if not exists idx_operacoes_status on public.operacoes (status);
alter table public.operacoes enable row level security;
create policy op_svc on public.operacoes for all to service_role using (true);
create policy op_sel on public.operacoes for select to authenticated using (true);
create policy op_ins on public.operacoes for insert to authenticated with check (true);
create policy op_upd on public.operacoes for update to authenticated using (true) with check (true);
create policy op_del on public.operacoes for delete to authenticated using (true);

-- ════════════════════════════════════════════════════════════════════════════
-- 3. SEED app_settings PARA CONFIG TELEGRAM
-- ════════════════════════════════════════════════════════════════════════════
INSERT INTO public.app_settings (chave, valor) VALUES
  ('config_telegram', '{}'::jsonb),
  ('config_sv_stats', '{}'::jsonb),
  ('config_roubos_historico', '[]'::jsonb)
ON CONFLICT (chave) DO NOTHING;
