-- 0079 — Broadcasts + notificações globais
-- Sistema de comunicação segmentada: por país, cidade, cargo

-- ── broadcasts ──────────────────────────────────────────────────────────────
create table if not exists public.broadcasts (
  id          bigint generated by default as identity primary key,
  titulo      text not null,
  corpo       text not null,
  tipo        text not null default 'info',        -- info, alerta, novidade, manutencao
  -- Segmentação (null = todos)
  pais        text,                                 -- 'BR', 'US', null=todos
  cidades     text[] default '{}',                  -- {'SP','CWB'}, {}=todas
  roles       text[] default '{}',                  -- {'guard','campo'}, {}=todos
  -- Metadata
  autor_uid   text,
  autor_nome  text,
  enviado_em  timestamptz not null default now(),
  push_enviado boolean not null default false
);
alter table public.broadcasts enable row level security;
create policy bc_svc on public.broadcasts for all to service_role using (true);
create policy bc_sel on public.broadcasts for select to authenticated using (true);
create policy bc_ins on public.broadcasts for insert to authenticated with check (true);

-- ── Ajustar RLS de notificacoes_app para notificações globais (uid IS NULL) ──
-- Permitir que authenticated leia notificações onde uid = seu OU uid IS NULL (broadcast)
do $$ begin
  if exists (select 1 from pg_policies where tablename='notificacoes_app' and policyname='notif_sel') then
    drop policy notif_sel on public.notificacoes_app;
  end if;
end $$;
create policy notif_sel on public.notificacoes_app
  for select to authenticated
  using (uid = auth.uid()::text or uid is null);

-- Adicionar colunas de segmentação em notificacoes_app para broadcasts
alter table public.notificacoes_app add column if not exists broadcast_id bigint references broadcasts(id);
alter table public.notificacoes_app add column if not exists cidade text;
alter table public.notificacoes_app add column if not exists role_alvo text;
